# ##############################################################################
# generateVersion.cmake
#
# CMake script invoked at BUILD time (via add_custom_target) to generate
# cErrorDriverVersion.h. Re-runs on every cmake --build invocation so the
# timestamp in PATCH is always current.
#
# Required inputs (passed via -D on the command line):
#   VERSION_MAJOR  — major version integer
#   VERSION_MINOR  — minor version integer
#   BUILD_TYPE     — "STATIC" or "DYNAMIC"
#   OUTPUT_FILE    — absolute path to write the generated header
# ##############################################################################

# Compute PATCH as MMYYHHMMSS (month, 2-digit year, hour, minute, second)
string(TIMESTAMP BUILD_DATE_TIME "%m%y%H%M%S")

set(HEADER_CONTENT
"/* *************************************************************
 * cErrorDriverVersion.h
 * Auto-generated by CMake at build time. DO NOT EDIT MANUALLY.
 * Regenerated on every cmake --build invocation.
 * Version: ${VERSION_MAJOR}.${VERSION_MINOR}.${BUILD_PATCH}.${BUILD_TYPE}
 ***************************************************************/
#ifndef C_ERROR_DRIVER_VERSION_H
#define C_ERROR_DRIVER_VERSION_H

/* Major version — incremented on breaking API changes */
#define ERROR_DRIVER_VERSION_MAJOR  ${VERSION_MAJOR}

/* Minor version — incremented on backward-compatible feature additions */
#define ERROR_DRIVER_VERSION_MINOR  ${VERSION_MINOR}

/* Patch — incremented on backward-compatible feature additions */
#define ERROR_DRIVER_VERSION_PATCH  ${BUILD_PATCH}

/* Build date/time — build timestamp encoded as MMYYHHMMSS */
#define ERROR_DRIVER_VERSION_BUILD_DATE_TIME  ${BUILD_DATE_TIME}

/* Build type — STATIC or DYNAMIC */
#define ERROR_DRIVER_VERSION_BUILD_TYPE  \"${BUILD_TYPE}\"

/* Composite version string: \"Major.Minor.MMYYHHMMSS.BuildType\"
 * Adjacent string-literal concatenation is resolved at compile time. */
#define ERROR_DRIVER_VERSION_STRING  \\
    \"${VERSION_MAJOR}.${VERSION_MINOR}.\" ERROR_DRIVER_VERSION_PATCH \".${BUILD_TYPE}\"

#endif /* C_ERROR_DRIVER_VERSION_H */
")

file(WRITE "${OUTPUT_FILE}" "${HEADER_CONTENT}")
message(STATUS "Generated ${OUTPUT_FILE}  [${VERSION_MAJOR}.${VERSION_MINOR}.${BUILD_PATCH}.${BUILD_TYPE}]")
